ERROR - 2025-03-14 04:14:03 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:14:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:15:18 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:15:18 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:16:26 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:16:26 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:17:43 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 1433, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:17:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:18:12 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:18:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:20:49 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 1433, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:20:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:30:49 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 04:30:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 04:55:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 04:55:49 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
ERROR - 2025-03-14 05:02:08 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 05:02:08 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
ERROR - 2025-03-14 05:02:09 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 05:02:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
ERROR - 2025-03-14 05:04:06 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 05:04:06 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
ERROR - 2025-03-14 05:04:07 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 05:04:07 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
CRITICAL - 2025-03-14 05:06:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES)
[Method: GET, Route: pruebadb]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 246.
 1 APPPATH\Controllers\PruebaDB.php(13): CodeIgniter\Database\MySQLi\Connection->connect()
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PruebaDB->index()
 3 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaDB))
 4 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 8 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
CRITICAL - 2025-03-14 05:06:40 --> [Caused by] mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES)
in SYSTEMPATH\Database\MySQLi\Connection.php on line 201.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
 2 APPPATH\Controllers\PruebaDB.php(13): CodeIgniter\Database\MySQLi\Connection->connect()
 3 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\PruebaDB->index()
 4 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\PruebaDB))
 5 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 8 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 9 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
ERROR - 2025-03-14 05:09:20 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run(Array)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', Array)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(360): CodeIgniter\CLI\Console->run()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#9 {main}
CRITICAL - 2025-03-14 05:09:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: CLI, Route: db:table]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseConnection.php(1525): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FROM `restaurant_db`')
 3 SYSTEMPATH\Commands\Database\ShowTableInfo.php(121): CodeIgniter\Database\BaseConnection->listTables()
 4 SYSTEMPATH\CLI\Commands.php(70): CodeIgniter\Commands\Database\ShowTableInfo->run([])
 5 SYSTEMPATH\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('db:table', [])
 6 SYSTEMPATH\Boot.php(360): CodeIgniter\CLI\Console->run()
 7 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
 8 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2025-03-14 18:18:45 --> Error connecting to the database: mysqli_sql_exception: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:201
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(201): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'restaurant_db', 3306, '', 0)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión in C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:246
Stack trace:
#0 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
#5 C:\xampp\htdocs\Restaurante-App\Restaurante-App\app\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
#6 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
#7 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
#8 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(334): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\Restaurante-App\Restaurante-App\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 C:\xampp\htdocs\Restaurante-App\Restaurante-App\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('C:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2025-03-14 18:18:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No se puede establecer una conexión ya que el equipo de destino denegó expresamente dicha conexión
[Method: GET, Route: configuracion/salon]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1649): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `Mesas`', [], false)
 3 SYSTEMPATH\Model.php(286): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(675): CodeIgniter\Model->doFindAll(0, 0)
 5 APPPATH\Controllers\Configuracion\Salon.php(14): CodeIgniter\BaseModel->findAll()
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Configuracion\Salon->index()
 7 SYSTEMPATH\CodeIgniter.php(507): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Configuracion\Salon))
 8 SYSTEMPATH\CodeIgniter.php(354): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(334): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\rewrite.php(44): require_once('C:\\xampp\\htdocs\\Restaurante-App\\Restaurante-App\\public\\index.php')
